# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3485915bdc4affd95cfe38748ff52d291076ef52a07eb7d088e246fa31cc3e65662ef739fe788ac1fdd9a206053a2780abaf5d3d4338eefa5197d0a599474884

test:
  secret_key_base: 9ff2de7c5f27417ffd3ecb184a9dcdd062d28e389aa11560ddedc92a4b7b103f231acdce8d6989041ebb49c25d93a2dca4f3a683bdc172e4f0ab75dd7e6d36ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
